In [2]:
# EXTRAÇÃO DE ONSETS (TEMPOS EXATOS DOS ESTÍMULOS)

import os
import pandas as pd
import mne
import warnings

# Silenciando avisos para terminal limpo
warnings.filterwarnings('ignore')
mne.set_log_level('WARNING')

print("\n" + "="*80)
print("Iniciando Mineração de Triggers (FF, FN, FR) no arquivo bruto...")
print("="*80)

# 1. Caminhos e Parâmetros
DIR_RAW = '../data/raw/'
DIR_RESULTS = '../results/'

# Lista de pacientes com falha conhecida (herdada do seu setup)
ARQUIVOS_EXCLUIDOS = ['control_14-sem marcacoes', 'TEA_M_22_1']
ESTIMULOS_ALVO = ['FF', 'FN', 'FR']

# Criar pasta de resultados se não existir
os.makedirs(DIR_RESULTS, exist_ok=True)

# 2. Varredura
arquivos_edf = sorted([f for f in os.listdir(DIR_RAW) if f.lower().endswith('.edf')])
dados_onsets = []
pacientes_processados = 0

for arquivo in arquivos_edf:
    paciente_id = arquivo.replace('.edf', '')
    
    # Pula pacientes excluídos
    if paciente_id in ARQUIVOS_EXCLUIDOS:
        continue
        
    caminho_completo = os.path.join(DIR_RAW, arquivo)
    
    try:
        # preload=False garante que só os metadados/eventos sejam lidos (super rápido)
        raw = mne.io.read_raw_edf(caminho_completo, preload=False, encoding='latin1', verbose=False)
        
        contador_estimulos = 0
        
        # Itera sobre todas as anotações do exame
        for ann in raw.annotations:
            descricao = ann['description'].strip().upper()
            
            # Se a descrição for exatamente FF, FN ou FR, nós extraímos
            if descricao in ESTIMULOS_ALVO:
                dados_onsets.append({
                    'Paciente_ID': paciente_id,
                    'Estimulo': descricao,
                    'Onset_Segundos': ann['onset']
                })
                contador_estimulos += 1
                
        print(f"[{paciente_id}] -> {contador_estimulos} estímulos mapeados.")
        pacientes_processados += 1
        
    except Exception as e:
        print(f"[ERRO] Falha ao processar {paciente_id}: {e}")

# 3. Consolidação e Exportação
df_onsets = pd.DataFrame(dados_onsets)

# Salva o arquivo CSV definitivo
caminho_csv = os.path.join(DIR_RESULTS, 'tabela_tempos_estimulos_faces.csv')
df_onsets.to_csv(caminho_csv, index=False)

print("\n" + "="*80)
print("EXTRAÇÃO CONCLUÍDA COM SUCESSO!")
print(f"Total de pacientes processados: {pacientes_processados}")
print(f"Total de estímulos isolados: {len(df_onsets)}")
print(f"Arquivo salvo em: {caminho_csv}")
print("="*80)

# Exibe as primeiras linhas para conferência visual imediata
display(df_onsets.head(10))

================================================================================
Iniciando Mineração de Triggers (FF, FN, FR) no arquivo bruto...
================================================================================
[TEA_G_26] -> 30 estímulos mapeados.
[TEA_G_28] -> 30 estímulos mapeados.
[TEA_G_30] -> 30 estímulos mapeados.
[TEA_G_40] -> 30 estímulos mapeados.
[TEA_L_16] -> 0 estímulos mapeados.
[TEA_L_17] -> 30 estímulos mapeados.
[TEA_L_24] -> 30 estímulos mapeados.
[TEA_L_25] -> 27 estímulos mapeados.
[TEA_L_27] -> 31 estímulos mapeados.
[TEA_L_29] -> 30 estímulos mapeados.
[TEA_L_32] -> 30 estímulos mapeados.
[TEA_L_46] -> 30 estímulos mapeados.
[TEA_M_15] -> 30 estímulos mapeados.
[TEA_M_18] -> 30 estímulos mapeados.
[TEA_M_19] -> 30 estímulos mapeados.
[TEA_M_20] -> 30 estímulos mapeados.
[TEA_M_21] -> 30 estímulos mapeados.
[TEA_M_22] -> 30 estímulos mapeados.
[control_12] -> 30 estímulos mapeados.
[control_13] -> 30 estímulos mapeados.
[control_35] -> 30 estímulos mapeados.
[control_36] -> 30 estímulos mapeados.
[control_37] -> 30 estímulos mapeados.
[control_38] -> 30 estímulos mapeados.
[control_39] -> 30 estímulos mapeados.
[control_41] -> 36 estímulos mapeados.
[control_42] -> 30 estímulos mapeados.
[control_43] -> 30 estímulos mapeados.
[control_44] -> 30 estímulos mapeados.
[control_47] -> 30 estímulos mapeados.
[control_48] -> 30 estímulos mapeados.
[control_49] -> 30 estímulos mapeados.
[control_50] -> 30 estímulos mapeados.
[control_51] -> 30 estímulos mapeados.
[control_54] -> 30 estímulos mapeados.
[control_55] -> 30 estímulos mapeados.
[control_56] -> 30 estímulos mapeados.
[control_57] -> 30 estímulos mapeados.
[control_58] -> 30 estímulos mapeados.
[control_59] -> 30 estímulos mapeados.
[control_60] -> 30 estímulos mapeados.
[control_61] -> 30 estímulos mapeados.

================================================================================
EXTRAÇÃO CONCLUÍDA COM SUCESSO!
Total de pacientes processados: 42
Total de estímulos isolados: 1234
Arquivo salvo em: ../results/tabela_tempos_estimulos_faces.csv
================================================================================

  Paciente_ID Estimulo  Onset_Segundos
0    TEA_G_26       FF          1820.0
1    TEA_G_26       FN          1824.0
2    TEA_G_26       FR          1828.0
3    TEA_G_26       FF          1832.0
4    TEA_G_26       FN          1836.0
5    TEA_G_26       FR          1840.0
6    TEA_G_26       FF          1844.0
7    TEA_G_26       FN          1848.0
8    TEA_G_26       FR          1852.0
9    TEA_G_26       FF          1857.0

In [2]:
# EXTRAÇÃO DE ONSETS (TEMPOS EXATOS DOS ESTÍMULOS) COM AUDITORIA TEMPORAL

import os
import pandas as pd
import mne
import warnings

# Silenciar avisos para manter o terminal limpo
warnings.filterwarnings('ignore')
mne.set_log_level('WARNING')

print("\n" + "="*80)
print("Iniciando Extração de Triggers (FF, FN, FR) com Cálculo de Delta T...")
print("="*80)

# 1. Parâmetros e Caminhos
DIR_RAW = '../data/raw/'
DIR_RESULTS = '../results/'

ARQUIVOS_EXCLUIDOS = ['control_14-sem marcacoes', 'TEA_M_22_1']
ESTIMULOS_ALVO = ['FF', 'FN', 'FR']

os.makedirs(DIR_RESULTS, exist_ok=True)

arquivos_edf = sorted([f for f in os.listdir(DIR_RAW) if f.lower().endswith('.edf')])
dados_onsets = []
pacientes_processados = 0

# 2. Varredura e Extração Lógica
for arquivo in arquivos_edf:
    paciente_id = arquivo.replace('.edf', '')
    
    if paciente_id in ARQUIVOS_EXCLUIDOS:
        continue
        
    caminho_completo = os.path.join(DIR_RAW, arquivo)
    
    try:
        raw = mne.io.read_raw_edf(caminho_completo, preload=False, encoding='latin1', verbose=False)
        
        contador_faces = 0
        ultimo_onset = None
        
        # Iterar sobre todas as anotações do exame temporalmente
        for ann in raw.annotations:
            descricao = ann['description'].strip().upper()
            
            # Se a descrição for FF, FN ou FR, capturamos as métricas
            if descricao in ESTIMULOS_ALVO:
                contador_faces += 1
                onset_atual = ann['onset']
                duracao = ann['duration']
                
                # Calcular a diferença de tempo desde o último estímulo
                if ultimo_onset is not None:
                    delta_t = onset_atual - ultimo_onset
                else:
                    delta_t = 0.0 # É o primeiro estímulo, logo não há intervalo anterior
                    
                dados_onsets.append({
                    'Paciente_ID': paciente_id,
                    'Face_Ordem': contador_faces,
                    'Estimulo': descricao,
                    'Onset_Segundos': round(onset_atual, 4),
                    'Duracao_Segundos': round(duracao, 4),
                    'Delta_T_Anterior_Segs': round(delta_t, 4)
                })
                
                # Atualizar a memória do último onset para o próximo ciclo
                ultimo_onset = onset_atual
                
        print(f"[{paciente_id}] -> {contador_faces} faces mapeadas.")
        pacientes_processados += 1
        
    except Exception as e:
        print(f"[ERRO] Falha ao processar {paciente_id}: {e}")

# 3. Consolidação e Exportação
df_onsets = pd.DataFrame(dados_onsets)

caminho_csv = os.path.join(DIR_RESULTS, 'tabela_tempos_estimulos_faces.csv')
df_onsets.to_csv(caminho_csv, index=False)

print("\n" + "="*80)
print("EXTRAÇÃO CONCLUÍDA!")
print(f"Total de pacientes processados: {pacientes_processados}")
print(f"Total de estímulos isolados: {len(df_onsets)}")
print(f"Ficheiro salvo em: {caminho_csv}")
print("="*80)

# Exibe as primeiras 10 linhas para conferência imediata
display(df_onsets.head(10))

================================================================================
Iniciando Extração de Triggers (FF, FN, FR) com Cálculo de Delta T...
================================================================================
[TEA_G_26] -> 30 faces mapeadas.
[TEA_G_28] -> 30 faces mapeadas.
[TEA_G_30] -> 30 faces mapeadas.
[TEA_G_40] -> 30 faces mapeadas.
[TEA_L_16] -> 0 faces mapeadas.
[TEA_L_17] -> 30 faces mapeadas.
[TEA_L_24] -> 30 faces mapeadas.
[TEA_L_25] -> 27 faces mapeadas.
[TEA_L_27] -> 31 faces mapeadas.
[TEA_L_29] -> 30 faces mapeadas.
[TEA_L_32] -> 30 faces mapeadas.
[TEA_L_46] -> 30 faces mapeadas.
[TEA_M_15] -> 30 faces mapeadas.
[TEA_M_18] -> 30 faces mapeadas.
[TEA_M_19] -> 30 faces mapeadas.
[TEA_M_20] -> 30 faces mapeadas.
[TEA_M_21] -> 30 faces mapeadas.
[TEA_M_22] -> 30 faces mapeadas.
[control_12] -> 30 faces mapeadas.
[control_13] -> 30 faces mapeadas.
[control_35] -> 30 faces mapeadas.
[control_36] -> 30 faces mapeadas.
[control_37] -> 30 faces mapeadas.
[control_38] -> 30 faces mapeadas.
[control_39] -> 30 faces mapeadas.
[control_41] -> 36 faces mapeadas.
[control_42] -> 30 faces mapeadas.
[control_43] -> 30 faces mapeadas.
[control_44] -> 30 faces mapeadas.
[control_47] -> 30 faces mapeadas.
[control_48] -> 30 faces mapeadas.
[control_49] -> 30 faces mapeadas.
[control_50] -> 30 faces mapeadas.
[control_51] -> 30 faces mapeadas.
[control_54] -> 30 faces mapeadas.
[control_55] -> 30 faces mapeadas.
[control_56] -> 30 faces mapeadas.
[control_57] -> 30 faces mapeadas.
[control_58] -> 30 faces mapeadas.
[control_59] -> 30 faces mapeadas.
[control_60] -> 30 faces mapeadas.
[control_61] -> 30 faces mapeadas.

================================================================================
EXTRAÇÃO CONCLUÍDA!
Total de pacientes processados: 42
Total de estímulos isolados: 1234
Ficheiro salvo em: ../results/tabela_tempos_estimulos_faces.csv
================================================================================

,Paciente_ID,Face_Ordem,Estimulo,Onset_Segundos,Duracao_Segundos,Delta_T_Anterior_Segs
0,TEA_G_26,1,FF,1820.0,0.0,0.0
1,TEA_G_26,2,FN,1824.0,0.0,4.0
2,TEA_G_26,3,FR,1828.0,0.0,4.0
3,TEA_G_26,4,FF,1832.0,0.0,4.0
4,TEA_G_26,5,FN,1836.0,0.0,4.0
5,TEA_G_26,6,FR,1840.0,0.0,4.0
6,TEA_G_26,7,FF,1844.0,0.0,4.0
7,TEA_G_26,8,FN,1848.0,0.0,4.0
8,TEA_G_26,9,FR,1852.0,0.0,4.0
9,TEA_G_26,10,FF,1857.0,0.0,5.0

In [4]:
# Exibe as primeiras 10 linhas para conferência imediata
display(df_onsets.head(30))

,Paciente_ID,Face_Ordem,Estimulo,Onset_Segundos,Duracao_Segundos,Delta_T_Anterior_Segs
0,TEA_G_26,1,FF,1820.0,0.0,0.0
1,TEA_G_26,2,FN,1824.0,0.0,4.0
2,TEA_G_26,3,FR,1828.0,0.0,4.0
3,TEA_G_26,4,FF,1832.0,0.0,4.0
4,TEA_G_26,5,FN,1836.0,0.0,4.0
5,TEA_G_26,6,FR,1840.0,0.0,4.0
6,TEA_G_26,7,FF,1844.0,0.0,4.0
7,TEA_G_26,8,FN,1848.0,0.0,4.0
8,TEA_G_26,9,FR,1852.0,0.0,4.0
9,TEA_G_26,10,FF,1857.0,0.0,5.0
10,TEA_G_26,11,FN,1861.0,0.0,4.0
11,TEA_G_26,12,FR,1865.0,0.0,4.0
12,TEA_G_26,13,FF,1869.0,0.0,4.0
13,TEA_G_26,14,FN,1873.0,0.0,4.0
14,TEA_G_26,15,FR,1877.0,0.0,4.0
15,TEA_G_26,16,FF,1881.0,0.0,4.0
16,TEA_G_26,17,FN,1885.0,0.0,4.0
17,TEA_G_26,18,FR,1889.0,0.0,4.0
18,TEA_G_26,19,FF,1893.0,0.0,4.0
19,TEA_G_26,20,FN,1897.0,0.0,4.0
20,TEA_G_26,21,FR,1901.0,0.0,4.0
21,TEA_G_26,22,FF,1905.0,0.0,4.0
22,TEA_G_26,23,FN,1909.0,0.0,4.0
23,TEA_G_26,24,FR,1913.0,0.0,4.0
24,TEA_G_26,25,FF,1917.0,0.0,4.0
25,TEA_G_26,26,FN,1921.0,0.0,4.0
26,TEA_G_26,27,FR,1925.0,0.0,4.0
27,TEA_G_26,28,FF,1929.0,0.0,4.0
28,TEA_G_26,29,FN,1933.0,0.0,4.0
29,TEA_G_26,30,FR,1937.0,0.0,4.0

In [5]:
import os
import mne
import collections
import warnings

# Silenciar avisos para manter o terminal limpo
warnings.filterwarnings('ignore')
mne.set_log_level('WARNING')

print("\n" + "="*80)
print("Iniciando Auditoria Forense de Marcadores nos Pacientes Anômalos...")
print("="*80)

# Parâmetros
DIR_RAW = '../data/raw/'
PACIENTES_AUDITORIA = ['TEA_L_16', 'TEA_L_25', 'TEA_L_27', 'control_41']

for paciente_id in PACIENTES_AUDITORIA:
    caminho_completo = os.path.join(DIR_RAW, f"{paciente_id}.edf")
    
    if not os.path.exists(caminho_completo):
        print(f"[AVISO] Arquivo não encontrado: {caminho_completo}")
        continue
        
    try:
        # Lê o ficheiro sem carregar os dados cerebrais para a memória (rápido)
        raw = mne.io.read_raw_edf(caminho_completo, preload=False, encoding='latin1', verbose=False)
        
        # Coleta absolutamente todas as descrições registadas
        todas_descricoes = [ann['description'].strip() for ann in raw.annotations]
        
        # Conta a frequência de cada marcador
        contagem = collections.Counter(todas_descricoes)
        
        print(f"\n--- Paciente: {paciente_id} ---")
        print(f"Total absoluto de eventos registados: {len(todas_descricoes)}")
        print("Detalhamento dos marcadores encontrados (Nome Exato -> Quantidade):")
        
        # Imprime do marcador que mais apareceu para o que menos apareceu
        for marcador, qtd in contagem.most_common():
            # Colocamos o marcador entre aspas simples para detetar espaços em branco acidentais
            print(f"  -> '{marcador}': {qtd} vezes")
            
    except Exception as e:
        print(f"[ERRO] Falha ao processar {paciente_id}: {e}")

print("\n" + "="*80)
print("AUDITORIA CONCLUÍDA.")
print("="*80)

================================================================================
Iniciando Auditoria Forense de Marcadores nos Pacientes Anômalos...
================================================================================

--- Paciente: TEA_L_16 ---
Total absoluto de eventos registados: 423
Detalhamento dos marcadores encontrados (Nome Exato -> Quantidade):
  -> 'Calibracao': 37 vezes
  -> 'TREM': 30 vezes
  -> 'FACE': 30 vezes
  -> 'MONTAGEM': 30 vezes
  -> 'VIDEO': 10 vezes
  -> 'PROJECAO': 10 vezes
  -> 'F': 10 vezes
  -> 'N': 10 vezes
  -> 'R': 10 vezes
  -> 'TREM GRANDE': 7 vezes
  -> 'A1+A2 OFF': 4 vezes
  -> 'IMP CHECK ON': 3 vezes
  -> 'IMP CHECK OFF': 3 vezes
  -> 'Segment: REC START AV EEG': 3 vezes
  -> 'Olhos abertos': 2 vezes
  -> 'Olhos Fechados': 2 vezes
  -> '+0.000000': 1 vezes
  -> 'Segment: REC START DB EEG': 1 vezes
  -> '+1.140000': 1 vezes
  -> '+3.920000': 1 vezes
  -> '+5.000000': 1 vezes
  -> '+7.000000': 1 vezes
  -> '+61.940000': 1 vezes
  -> '+63.000000': 1 vezes
  -> '+73.000000': 1 vezes
  -> '+168.160000': 1 vezes
  -> '+170.000000': 1 vezes
  -> '+173.000000': 1 vezes
  -> '+174.040000': 1 vezes
  -> '+263.260000': 1 vezes
  -> '+268.640000': 1 vezes
  -> '+274.020000': 1 vezes
  -> '+279.860000': 1 vezes
  -> '+365.000000': 1 vezes
  -> '+366.020000': 1 vezes
  -> 'Recording Gap 0000:07:18': 1 vezes
  -> 'BASAL 1 INICIO': 1 vezes
  -> '+546.730000': 1 vezes
  -> 'BASAL 1 FINAL': 1 vezes
  -> '+604.000000': 1 vezes
  -> '+605.000000': 1 vezes
  -> 'Recording Gap 0000:01:26': 1 vezes
  -> '+642.590000': 1 vezes
  -> 'AJUST ELET': 1 vezes
  -> '+654.735000': 1 vezes
  -> '+683.995000': 1 vezes
  -> '+684.215000': 1 vezes
  -> 'CALIBRACAO 1': 1 vezes
  -> '+702.390000': 1 vezes
  -> '+718.810000': 1 vezes
  -> '+724.410000': 1 vezes
  -> '+730.560000': 1 vezes
  -> '+735.670000': 1 vezes
  -> '+740.550000': 1 vezes
  -> '+747.210000': 1 vezes
  -> '+751.080000': 1 vezes
  -> '+756.830000': 1 vezes
  -> '+763.300000': 1 vezes
  -> '+783.715000': 1 vezes
  -> '+784.015000': 1 vezes
  -> 'CALIBRACAO 2': 1 vezes
  -> '+820.800000': 1 vezes
  -> '+838.030000': 1 vezes
  -> '+843.670000': 1 vezes
  -> '+850.370000': 1 vezes
  -> '+854.170000': 1 vezes
  -> '+860.280000': 1 vezes
  -> '+865.910000': 1 vezes
  -> '+870.370000': 1 vezes
  -> '+876.150000': 1 vezes
  -> '+883.810000': 1 vezes
  -> '+887.060000': 1 vezes
  -> '+893.090000': 1 vezes
  -> '+898.950000': 1 vezes
  -> '+923.390000': 1 vezes
  -> '+944.320000': 1 vezes
  -> '+970.800000': 1 vezes
  -> '+1012.980000': 1 vezes
  -> '+1104.900000': 1 vezes
  -> '+1124.525000': 1 vezes
  -> '+1143.725000': 1 vezes
  -> '+1186.115000': 1 vezes
  -> '+1233.585000': 1 vezes
  -> '+1253.895000': 1 vezes
  -> '+1304.020000': 1 vezes
  -> '+1344.300000': 1 vezes
  -> '+1364.390000': 1 vezes
  -> '+1393.845000': 1 vezes
  -> '+1413.120000': 1 vezes
  -> '+1445.870000': 1 vezes
  -> '+1482.350000': 1 vezes
  -> '+1533.400000': 1 vezes
  -> '+1560.000000': 1 vezes
  -> '+1561.060000': 1 vezes
  -> 'Recording Gap 0000:02:42': 1 vezes
  -> '+1571.775000': 1 vezes
  -> '+1612.170000': 1 vezes
  -> '+1632.315000': 1 vezes
  -> '+1642.695000': 1 vezes
  -> '+1662.490000': 1 vezes
  -> '+1692.550000': 1 vezes
  -> '+1722.400000': 1 vezes
  -> '+1742.500000': 1 vezes
  -> '+1782.890000': 1 vezes
  -> '+1792.540000': 1 vezes
  -> '+1842.320000': 1 vezes
  -> '+1863.110000': 1 vezes
  -> '+2122.540000': 1 vezes
  -> 'CALIBRACAO 3': 1 vezes
  -> '+2172.090000': 1 vezes
  -> '+2189.680000': 1 vezes
  -> '+2195.200000': 1 vezes
  -> '+2201.280000': 1 vezes
  -> '+2208.530000': 1 vezes
  -> '+2211.530000': 1 vezes
  -> '+2217.820000': 1 vezes
  -> '+2221.880000': 1 vezes
  -> '+2227.660000': 1 vezes
  -> '+2234.280000': 1 vezes
  -> '+2281.325000': 1 vezes
  -> '+2311.650000': 1 vezes
  -> '+2341.735000': 1 vezes
  -> '+2382.175000': 1 vezes
  -> 'CALIBRACAO 4': 1 vezes
  -> '+2412.280000': 1 vezes
  -> '+2430.135000': 1 vezes
  -> '+2431.960000': 1 vezes
  -> '+2434.160000': 1 vezes
  -> '+2438.110000': 1 vezes
  -> '+2442.190000': 1 vezes
  -> '+2443.340000': 1 vezes
  -> '+2445.995000': 1 vezes
  -> '+2447.300000': 1 vezes
  -> '+2450.260000': 1 vezes
  -> '+2452.280000': 1 vezes
  -> '+2454.285000': 1 vezes
  -> '+2455.200000': 1 vezes
  -> '+2458.335000': 1 vezes
  -> '+2459.220000': 1 vezes
  -> '+2462.300000': 1 vezes
  -> '+2463.220000': 1 vezes
  -> '+2466.320000': 1 vezes
  -> '+2467.160000': 1 vezes
  -> '+2470.380000': 1 vezes
  -> '+2474.435000': 1 vezes
  -> '+2475.100000': 1 vezes
  -> '+2478.430000': 1 vezes
  -> '+2479.260000': 1 vezes
  -> '+2482.455000': 1 vezes
  -> '+2483.080000': 1 vezes
  -> '+2486.560000': 1 vezes
  -> '+2487.210000': 1 vezes
  -> '+2490.610000': 1 vezes
  -> '+2491.160000': 1 vezes
  -> '+2494.670000': 1 vezes
  -> '+2495.120000': 1 vezes
  -> '+2498.695000': 1 vezes
  -> '+2499.210000': 1 vezes
  -> '+2502.620000': 1 vezes
  -> '+2503.090000': 1 vezes
  -> '+2506.680000': 1 vezes
  -> '+2507.150000': 1 vezes
  -> '+2510.745000': 1 vezes
  -> '+2511.320000': 1 vezes
  -> '+2514.800000': 1 vezes
  -> '+2515.310000': 1 vezes
  -> '+2518.820000': 1 vezes
  -> '+2519.520000': 1 vezes
  -> '+2522.885000': 1 vezes
  -> '+2523.430000': 1 vezes
  -> '+2526.830000': 1 vezes
  -> '+2527.460000': 1 vezes
  -> '+2530.865000': 1 vezes
  -> '+2531.260000': 1 vezes
  -> '+2534.960000': 1 vezes
  -> '+2535.360000': 1 vezes
  -> '+2538.935000': 1 vezes
  -> '+2539.310000': 1 vezes
  -> '+2542.995000': 1 vezes
  -> '+2543.540000': 1 vezes
  -> '+2547.015000': 1 vezes
  -> '+2553.170000': 1 vezes
  -> '+2555.960000': 1 vezes
  -> '+2560.280000': 1 vezes
  -> '+2563.820000': 1 vezes
  -> '+2568.170000': 1 vezes
  -> '+2572.640000': 1 vezes
  -> '+2576.040000': 1 vezes
  -> '+2580.240000': 1 vezes
  -> '+2584.090000': 1 vezes
  -> '+2588.110000': 1 vezes
  -> '+2592.180000': 1 vezes
  -> '+2596.240000': 1 vezes
  -> '+2600.120000': 1 vezes
  -> '+2604.280000': 1 vezes
  -> '+2608.120000': 1 vezes
  -> '+2612.080000': 1 vezes
  -> '+2616.110000': 1 vezes
  -> '+2620.180000': 1 vezes
  -> '+2624.430000': 1 vezes
  -> '+2628.380000': 1 vezes
  -> '+2661.195000': 1 vezes
  -> 'CALIBRACAO 5': 1 vezes
  -> '+2702.210000': 1 vezes
  -> '+2720.430000': 1 vezes
  -> '+2724.670000': 1 vezes
  -> '+2727.740000': 1 vezes
  -> '+2731.660000': 1 vezes
  -> '+2735.720000': 1 vezes
  -> '+2739.680000': 1 vezes
  -> '+2743.760000': 1 vezes
  -> '+2747.840000': 1 vezes
  -> '+2751.960000': 1 vezes
  -> '+2756.240000': 1 vezes
  -> '+2760.260000': 1 vezes
  -> '+2764.040000': 1 vezes
  -> '+2768.140000': 1 vezes
  -> '+2772.120000': 1 vezes
  -> '+2776.220000': 1 vezes
  -> '+2780.320000': 1 vezes
  -> '+2784.340000': 1 vezes
  -> '+2788.340000': 1 vezes
  -> '+2792.360000': 1 vezes
  -> '+2796.450000': 1 vezes
  -> '+2800.540000': 1 vezes
  -> '+2804.870000': 1 vezes
  -> '+2808.460000': 1 vezes
  -> '+2812.520000': 1 vezes
  -> '+2816.580000': 1 vezes
  -> '+2820.780000': 1 vezes
  -> '+2824.620000': 1 vezes
  -> '+2828.720000': 1 vezes
  -> '+2832.890000': 1 vezes
  -> '+2836.740000': 1 vezes
  -> '+2842.420000': 1 vezes
  -> 'BASAL 2 INICIO': 1 vezes
  -> '+3022.035000': 1 vezes
  -> 'BASAL 2 FINAL': 1 vezes

--- Paciente: TEA_L_25 ---
Total absoluto de eventos registados: 395
Detalhamento dos marcadores encontrados (Nome Exato -> Quantidade):
  -> 'TREM': 34 vezes
  -> 'FACE': 30 vezes
  -> 'MONTAGEM': 30 vezes
  -> 'VIDEO': 14 vezes
  -> 'PROJECAO': 14 vezes
  -> 'Calibracao': 10 vezes
  -> 'FF': 9 vezes
  -> 'FN': 9 vezes
  -> 'FR': 9 vezes
  -> 'IMAGEM GRANDE': 7 vezes
  -> 'IMP CHECK ON': 3 vezes
  -> 'IMP CHECK OFF': 3 vezes
  -> 'PROJETO 1': 3 vezes
  -> 'Segment: REC START DB EEG': 2 vezes
  -> 'A1+A2 OFF': 2 vezes
  -> '2': 2 vezes
  -> '+0.000000': 1 vezes
  -> '+1.160000': 1 vezes
  -> '+12.460000': 1 vezes
  -> '+14.000000': 1 vezes
  -> '+15.000000': 1 vezes
  -> '+20.000000': 1 vezes
  -> '+22.000000': 1 vezes
  -> '+23.000000': 1 vezes
  -> '+249.935000': 1 vezes
  -> 'BASAL 1 INICIO': 1 vezes
  -> '+309.830000': 1 vezes
  -> 'BASAL1 2': 1 vezes
  -> '+369.795000': 1 vezes
  -> 'BASAL 1 3': 1 vezes
  -> '+429.055000': 1 vezes
  -> 'BASAL 1 FINAL': 1 vezes
  -> '+431.000000': 1 vezes
  -> '+432.020000': 1 vezes
  -> 'Recording Gap 0000:01:04': 1 vezes
  -> '+438.165000': 1 vezes
  -> '+453.860000': 1 vezes
  -> '+455.000000': 1 vezes
  -> '+456.000000': 1 vezes
  -> '+527.430000': 1 vezes
  -> '+616.650000': 1 vezes
  -> '+656.565000': 1 vezes
  -> 'PROJETO 1 QUE TRAVOU': 1 vezes
  -> '+671.500000': 1 vezes
  -> '+707.220000': 1 vezes
  -> 'CALIBRACAO 1': 1 vezes
  -> '+708.315000': 1 vezes
  -> 'PROJETO 2 SEM MARCAR ON/OFF': 1 vezes
  -> '+760.800000': 1 vezes
  -> '+776.035000': 1 vezes
  -> '+786.740000': 1 vezes
  -> '+791.700000': 1 vezes
  -> '+795.115000': 1 vezes
  -> '+802.540000': 1 vezes
  -> '+807.620000': 1 vezes
  -> '+812.340000': 1 vezes
  -> '+819.220000': 1 vezes
  -> '+824.120000': 1 vezes
  -> '+828.440000': 1 vezes
  -> '+834.280000': 1 vezes
  -> '+840.500000': 1 vezes
  -> '+847.370000': 1 vezes
  -> '3': 1 vezes
  -> 'CALIBRACAO 2': 1 vezes
  -> '+870.940000': 1 vezes
  -> 'PROJETO 3': 1 vezes
  -> '+903.700000': 1 vezes
  -> '+924.660000': 1 vezes
  -> '+929.480000': 1 vezes
  -> '+935.480000': 1 vezes
  -> '+939.700000': 1 vezes
  -> '+945.840000': 1 vezes
  -> '+952.130000': 1 vezes
  -> '+956.560000': 1 vezes
  -> '+962.320000': 1 vezes
  -> '+968.410000': 1 vezes
  -> '1': 1 vezes
  -> '+969.035000': 1 vezes
  -> 'CALIBRACAO 3': 1 vezes
  -> '+979.280000': 1 vezes
  -> '+1027.620000': 1 vezes
  -> '+1046.610000': 1 vezes
  -> '+1052.240000': 1 vezes
  -> '+1058.320000': 1 vezes
  -> '+1062.780000': 1 vezes
  -> '+1068.700000': 1 vezes
  -> '+1075.000000': 1 vezes
  -> '+1079.170000': 1 vezes
  -> '+1085.390000': 1 vezes
  -> '+1086.580000': 1 vezes
  -> 'CALIBRACAO 4': 1 vezes
  -> '+1091.240000': 1 vezes
  -> '+1096.845000': 1 vezes
  -> '+1097.155000': 1 vezes
  -> 'PROJETO 2': 1 vezes
  -> 'REPETIDO PROJETO 2': 1 vezes
  -> '+1155.700000': 1 vezes
  -> '+1175.980000': 1 vezes
  -> '+1182.420000': 1 vezes
  -> '+1187.800000': 1 vezes
  -> '+1191.920000': 1 vezes
  -> '+1197.670000': 1 vezes
  -> '+1204.040000': 1 vezes
  -> '+1208.320000': 1 vezes
  -> '+1213.860000': 1 vezes
  -> '+1219.420000': 1 vezes
  -> '+1224.520000': 1 vezes
  -> '+1229.740000': 1 vezes
  -> '+1235.740000': 1 vezes
  -> '+1246.965000': 1 vezes
  -> '+1247.265000': 1 vezes
  -> '4': 1 vezes
  -> 'CALIBRACAO 5': 1 vezes
  -> '+1257.555000': 1 vezes
  -> 'PROJETO 4': 1 vezes
  -> '+1299.040000': 1 vezes
  -> '+1317.005000': 1 vezes
  -> '+1318.610000': 1 vezes
  -> '+1321.060000': 1 vezes
  -> '+1325.125000': 1 vezes
  -> '+1326.110000': 1 vezes
  -> '+1329.140000': 1 vezes
  -> '+1330.170000': 1 vezes
  -> '+1334.420000': 1 vezes
  -> '+1337.230000': 1 vezes
  -> '+1338.440000': 1 vezes
  -> '+1341.265000': 1 vezes
  -> '+1342.120000': 1 vezes
  -> '+1346.620000': 1 vezes
  -> '+1349.380000': 1 vezes
  -> '+1350.060000': 1 vezes
  -> '+1353.445000': 1 vezes
  -> '+1354.120000': 1 vezes
  -> '+1358.340000': 1 vezes
  -> '+1361.415000': 1 vezes
  -> '+1362.260000': 1 vezes
  -> '+1365.470000': 1 vezes
  -> '+1366.170000': 1 vezes
  -> '+1369.500000': 1 vezes
  -> '+1370.200000': 1 vezes
  -> '+1373.525000': 1 vezes
  -> '+1374.110000': 1 vezes
  -> '+1377.610000': 1 vezes
  -> '+1378.240000': 1 vezes
  -> '+1381.635000': 1 vezes
  -> '+1382.260000': 1 vezes
  -> '+1385.620000': 1 vezes
  -> '+1386.180000': 1 vezes
  -> '+1389.625000': 1 vezes
  -> '+1390.200000': 1 vezes
  -> '+1393.680000': 1 vezes
  -> '+1394.160000': 1 vezes
  -> '+1397.700000': 1 vezes
  -> '+1398.260000': 1 vezes
  -> '+1401.755000': 1 vezes
  -> '+1402.390000': 1 vezes
  -> '+1405.795000': 1 vezes
  -> '+1406.780000': 1 vezes
  -> '+1409.865000': 1 vezes
  -> '+1410.320000': 1 vezes
  -> '+1413.905000': 1 vezes
  -> '+1414.560000': 1 vezes
  -> '+1417.970000': 1 vezes
  -> '+1418.450000': 1 vezes
  -> '+1422.000000': 1 vezes
  -> '+1426.065000': 1 vezes
  -> '+1430.120000': 1 vezes
  -> '+1434.040000': 1 vezes
  -> '+1439.890000': 1 vezes
  -> '+1443.110000': 1 vezes
  -> '+1446.660000': 1 vezes
  -> '+1450.740000': 1 vezes
  -> '+1454.700000': 1 vezes
  -> '+1458.740000': 1 vezes
  -> '+1462.800000': 1 vezes
  -> '+1467.120000': 1 vezes
  -> '+1470.760000': 1 vezes
  -> '+1475.100000': 1 vezes
  -> '+1478.950000': 1 vezes
  -> '+1483.380000': 1 vezes
  -> '+1487.100000': 1 vezes
  -> '+1491.020000': 1 vezes
  -> '+1494.980000': 1 vezes
  -> '+1499.100000': 1 vezes
  -> '+1502.980000': 1 vezes
  -> '+1507.260000': 1 vezes
  -> '+1511.100000': 1 vezes
  -> '+1515.240000': 1 vezes
  -> '+1517.235000': 1 vezes
  -> '5': 1 vezes
  -> '+1528.295000': 1 vezes
  -> 'PROJETO 5': 1 vezes
  -> '+1606.995000': 1 vezes
  -> '+1607.290000': 1 vezes
  -> 'CALIBRACAO 6': 1 vezes
  -> '+1637.360000': 1 vezes
  -> '+1658.480000': 1 vezes
  -> '+1661.320000': 1 vezes
  -> '+1665.420000': 1 vezes
  -> '+1668.790000': 1 vezes
  -> '+1672.890000': 1 vezes
  -> '+1677.530000': 1 vezes
  -> '+1680.860000': 1 vezes
  -> '+1684.920000': 1 vezes
  -> '+1689.120000': 1 vezes
  -> '+1693.120000': 1 vezes
  -> '+1696.920000': 1 vezes
  -> '+1701.475000': 1 vezes
  -> '+1705.950000': 1 vezes
  -> '+1709.730000': 1 vezes
  -> '+1714.920000': 1 vezes
  -> '+1717.810000': 1 vezes
  -> '+1721.790000': 1 vezes
  -> '+1725.420000': 1 vezes
  -> '+1729.440000': 1 vezes
  -> '+1733.680000': 1 vezes
  -> '+1737.260000': 1 vezes
  -> '+1741.360000': 1 vezes
  -> '+1745.980000': 1 vezes
  -> '+1749.480000': 1 vezes
  -> '+1753.660000': 1 vezes
  -> '+1757.860000': 1 vezes
  -> '+1761.670000': 1 vezes
  -> '+1766.020000': 1 vezes
  -> '+1770.450000': 1 vezes
  -> '+1773.960000': 1 vezes
  -> '+1810.140000': 1 vezes
  -> 'BASAL 2 INICIO': 1 vezes
  -> '+1990.040000': 1 vezes
  -> 'BASAL 2 FINAL': 1 vezes

--- Paciente: TEA_L_27 ---
Total absoluto de eventos registados: 380
Detalhamento dos marcadores encontrados (Nome Exato -> Quantidade):
  -> 'TREM': 30 vezes
  -> 'FACE': 30 vezes
  -> 'MONTAGEM': 30 vezes
  -> 'FR': 11 vezes
  -> 'VIDEO': 10 vezes
  -> 'PROJECAO': 10 vezes
  -> 'FF': 10 vezes
  -> 'FN': 10 vezes
  -> 'IMP CHECK ON': 5 vezes
  -> 'IMP CHECK OFF': 5 vezes
  -> 'Calibracao': 5 vezes
  -> 'IMAGEM GRANDE': 5 vezes
  -> 'Olhos abertos': 3 vezes
  -> 'Segment: REC START DB EEG': 2 vezes
  -> 'A1+A2 OFF': 2 vezes
  -> 'Olhos Fechados': 2 vezes
  -> '+0.000000': 1 vezes
  -> '+1.140000': 1 vezes
  -> '+31.330000': 1 vezes
  -> '+33.000000': 1 vezes
  -> '+35.000000': 1 vezes
  -> '+78.700000': 1 vezes
  -> '+80.000000': 1 vezes
  -> '+99.000000': 1 vezes
  -> '+100.540000': 1 vezes
  -> 'basal': 1 vezes
  -> '+360.560000': 1 vezes
  -> '+362.000000': 1 vezes
  -> '+363.000000': 1 vezes
  -> '+368.270000': 1 vezes
  -> '+374.310000': 1 vezes
  -> '+387.810000': 1 vezes
  -> '+394.200000': 1 vezes
  -> '+407.280000': 1 vezes
  -> '+442.325000': 1 vezes
  -> 'BASAL 1 INICIO': 1 vezes
  -> '+622.010000': 1 vezes
  -> 'BASAL 1 FINAL': 1 vezes
  -> '+623.000000': 1 vezes
  -> '+624.020000': 1 vezes
  -> 'Recording Gap 0000:02:46': 1 vezes
  -> '+643.780000': 1 vezes
  -> 'projeto 1': 1 vezes
  -> '+664.230000': 1 vezes
  -> '1': 1 vezes
  -> 'CALIBRACAO 1': 1 vezes
  -> 'PROJETO 1': 1 vezes
  -> '+685.950000': 1 vezes
  -> '+687.000000': 1 vezes
  -> '+690.000000': 1 vezes
  -> '+714.380000': 1 vezes
  -> '+733.180000': 1 vezes
  -> '+739.300000': 1 vezes
  -> '+745.440000': 1 vezes
  -> '+750.920000': 1 vezes
  -> '+756.600000': 1 vezes
  -> '+762.000000': 1 vezes
  -> '+766.540000': 1 vezes
  -> '+772.300000': 1 vezes
  -> '+777.830000': 1 vezes
  -> '+782.830000': 1 vezes
  -> 'projeto 2': 1 vezes
  -> '+783.190000': 1 vezes
  -> '2': 1 vezes
  -> 'CALIBRACAO 2': 1 vezes
  -> 'PROJETO 2': 1 vezes
  -> '+855.760000': 1 vezes
  -> '+877.920000': 1 vezes
  -> '+883.920000': 1 vezes
  -> '+890.060000': 1 vezes
  -> '+894.240000': 1 vezes
  -> '+899.480000': 1 vezes
  -> '+905.950000': 1 vezes
  -> '+910.560000': 1 vezes
  -> '+915.800000': 1 vezes
  -> '+921.760000': 1 vezes
  -> '+927.060000': 1 vezes
  -> '+932.330000': 1 vezes
  -> '+938.480000': 1 vezes
  -> '+943.335000': 1 vezes
  -> 'projeto 3': 1 vezes
  -> '+944.215000': 1 vezes
  -> 'CALIBRACAO 3': 1 vezes
  -> 'PROJETO 3': 1 vezes
  -> '+954.110000': 1 vezes
  -> '3': 1 vezes
  -> '+1026.940000': 1 vezes
  -> '+1047.610000': 1 vezes
  -> '+1053.100000': 1 vezes
  -> '+1059.020000': 1 vezes
  -> '+1063.230000': 1 vezes
  -> '+1069.190000': 1 vezes
  -> '+1075.600000': 1 vezes
  -> '+1079.840000': 1 vezes
  -> '+1085.800000': 1 vezes
  -> '+1091.690000': 1 vezes
  -> '+1093.215000': 1 vezes
  -> 'projeto 4': 1 vezes
  -> '+1103.300000': 1 vezes
  -> '4': 1 vezes
  -> '+1104.005000': 1 vezes
  -> 'CALIBRACAO 4': 1 vezes
  -> 'PROJETO 4': 1 vezes
  -> '+1159.620000': 1 vezes
  -> '+1179.340000': 1 vezes
  -> '+1180.620000': 1 vezes
  -> '+1183.420000': 1 vezes
  -> '+1184.620000': 1 vezes
  -> '+1187.290000': 1 vezes
  -> '+1188.760000': 1 vezes
  -> '+1191.360000': 1 vezes
  -> '+1193.690000': 1 vezes
  -> '+1195.420000': 1 vezes
  -> '+1197.140000': 1 vezes
  -> '+1199.470000': 1 vezes
  -> '+1200.970000': 1 vezes
  -> '+1203.425000': 1 vezes
  -> '+1207.560000': 1 vezes
  -> '+1208.730000': 1 vezes
  -> '+1211.580000': 1 vezes
  -> '+1212.340000': 1 vezes
  -> '+1215.640000': 1 vezes
  -> '+1216.340000': 1 vezes
  -> '+1219.600000': 1 vezes
  -> '+1220.920000': 1 vezes
  -> '+1223.620000': 1 vezes
  -> '+1224.320000': 1 vezes
  -> '+1227.680000': 1 vezes
  -> '+1228.420000': 1 vezes
  -> '+1231.700000': 1 vezes
  -> '+1232.690000': 1 vezes
  -> '+1235.765000': 1 vezes
  -> '+1236.530000': 1 vezes
  -> '+1239.790000': 1 vezes
  -> '+1240.450000': 1 vezes
  -> '+1243.855000': 1 vezes
  -> '+1244.660000': 1 vezes
  -> '+1247.925000': 1 vezes
  -> '+1248.500000': 1 vezes
  -> '+1251.820000': 1 vezes
  -> '+1252.420000': 1 vezes
  -> '+1255.915000': 1 vezes
  -> '+1256.690000': 1 vezes
  -> '+1259.925000': 1 vezes
  -> '+1261.160000': 1 vezes
  -> '+1263.945000': 1 vezes
  -> '+1264.820000': 1 vezes
  -> '+1268.040000': 1 vezes
  -> '+1272.105000': 1 vezes
  -> '+1273.420000': 1 vezes
  -> '+1276.120000': 1 vezes
  -> '+1277.290000': 1 vezes
  -> '+1280.185000': 1 vezes
  -> '+1284.125000': 1 vezes
  -> '+1285.190000': 1 vezes
  -> '+1288.165000': 1 vezes
  -> '+1289.160000': 1 vezes
  -> '+1292.220000': 1 vezes
  -> '+1296.245000': 1 vezes
  -> '+1297.210000': 1 vezes
  -> '+1300.305000': 1 vezes
  -> '+1302.440000': 1 vezes
  -> '+1305.230000': 1 vezes
  -> '+1309.040000': 1 vezes
  -> '+1312.760000': 1 vezes
  -> '+1317.010000': 1 vezes
  -> '+1321.030000': 1 vezes
  -> '+1325.020000': 1 vezes
  -> '+1329.080000': 1 vezes
  -> '+1333.070000': 1 vezes
  -> '+1337.350000': 1 vezes
  -> '+1341.640000': 1 vezes
  -> '+1345.320000': 1 vezes
  -> '+1349.320000': 1 vezes
  -> '+1353.700000': 1 vezes
  -> '+1357.440000': 1 vezes
  -> '+1361.570000': 1 vezes
  -> '+1365.960000': 1 vezes
  -> '+1369.730000': 1 vezes
  -> '+1373.790000': 1 vezes
  -> '+1377.420000': 1 vezes
  -> '+1382.250000': 1 vezes
  -> 'projeto 5': 1 vezes
  -> '+1383.410000': 1 vezes
  -> '5': 1 vezes
  -> '+1384.050000': 1 vezes
  -> 'CALIBRACAO 5': 1 vezes
  -> 'PROJETO 5': 1 vezes
  -> '+1451.420000': 1 vezes
  -> '+1475.280000': 1 vezes
  -> '+1478.020000': 1 vezes
  -> '+1481.960000': 1 vezes
  -> '+1485.920000': 1 vezes
  -> '+1489.950000': 1 vezes
  -> '+1494.450000': 1 vezes
  -> '+1498.030000': 1 vezes
  -> '+1502.140000': 1 vezes
  -> '+1506.420000': 1 vezes
  -> '+1510.000000': 1 vezes
  -> '+1514.750000': 1 vezes
  -> '+1518.670000': 1 vezes
  -> '+1522.460000': 1 vezes
  -> '+1526.790000': 1 vezes
  -> '+1530.920000': 1 vezes
  -> '+1534.580000': 1 vezes
  -> '+1538.570000': 1 vezes
  -> '+1543.290000': 1 vezes
  -> '+1546.680000': 1 vezes
  -> '+1550.680000': 1 vezes
  -> '+1554.730000': 1 vezes
  -> '+1558.610000': 1 vezes
  -> '+1562.640000': 1 vezes

In [6]:
import os
import pandas as pd
import mne
import warnings

warnings.filterwarnings('ignore')
mne.set_log_level('WARNING')

print("\n" + "="*80)
print("Iniciando Extração Definitiva (Com Correções Forenses)...")
print("="*80)

DIR_RAW = '../data/raw/'
DIR_RESULTS = '../results/'

# Pacientes a excluir (os mesmos de antes)
ARQUIVOS_EXCLUIDOS = ['control_14-sem marcacoes', 'TEA_M_22_1']

# Expandimos o dicionário de estímulos para incluir o TEA_L_16 ('F', 'N', 'R')
ESTIMULOS_ALVO = ['FF', 'FN', 'FR', 'F', 'N', 'R']

os.makedirs(DIR_RESULTS, exist_ok=True)
arquivos_edf = sorted([f for f in os.listdir(DIR_RAW) if f.lower().endswith('.edf')])
dados_onsets = []
pacientes_processados = 0

for arquivo in arquivos_edf:
    paciente_id = arquivo.replace('.edf', '')
    if paciente_id in ARQUIVOS_EXCLUIDOS: continue
        
    caminho_completo = os.path.join(DIR_RAW, arquivo)
    
    try:
        raw = mne.io.read_raw_edf(caminho_completo, preload=False, encoding='latin1', verbose=False)
        contador_faces = 0
        ultimo_onset = None
        
        # REGRA ESPECIAL PARA TEA_L_25: Usar o marcador genérico 'FACE'
        if paciente_id == 'TEA_L_25':
            for ann in raw.annotations:
                descricao = ann['description'].strip().upper()
                if descricao == 'FACE':
                    contador_faces += 1
                    onset_atual = ann['onset']
                    duracao = ann['duration']
                    delta_t = onset_atual - ultimo_onset if ultimo_onset is not None else 0.0
                    
                    # Deduzindo a emoção pela ordem (Blocos de 10: FF, depois FN, depois FR)
                    if contador_faces <= 10: estimulo_deduzido = 'FF'
                    elif contador_faces <= 20: estimulo_deduzido = 'FN'
                    else: estimulo_deduzido = 'FR'

                    dados_onsets.append({
                        'Paciente_ID': paciente_id,
                        'Face_Ordem': contador_faces,
                        'Estimulo': estimulo_deduzido,
                        'Onset_Segundos': round(onset_atual, 4),
                        'Duracao_Segundos': round(duracao, 4),
                        'Delta_T_Anterior_Segs': round(delta_t, 4)
                    })
                    ultimo_onset = onset_atual
            print(f"[{paciente_id}] -> {contador_faces} faces recuperadas via 'FACE'.")
            pacientes_processados += 1
            continue # Pula para o próximo paciente
            
        # EXTRAÇÃO PADRÃO (Com filtro de duplo clique para TEA_L_27 e control_41)
        for ann in raw.annotations:
            descricao = ann['description'].strip().upper()
            
            if descricao in ESTIMULOS_ALVO:
                onset_atual = ann['onset']
                delta_t = onset_atual - ultimo_onset if ultimo_onset is not None else 0.0
                
                # FILTRO DE DUPLO CLIQUE: Se a diferença for menor que 2 segundos, é erro do investigador. Ignora.
                if ultimo_onset is not None and delta_t < 2.0:
                    continue
                    
                contador_faces += 1
                duracao = ann['duration']
                
                # Normalizando as letras do TEA_L_16 para o padrão oficial
                if descricao == 'F': descricao = 'FF'
                if descricao == 'N': descricao = 'FN'
                if descricao == 'R': descricao = 'FR'
                
                dados_onsets.append({
                    'Paciente_ID': paciente_id,
                    'Face_Ordem': contador_faces,
                    'Estimulo': descricao,
                    'Onset_Segundos': round(onset_atual, 4),
                    'Duracao_Segundos': round(duracao, 4),
                    'Delta_T_Anterior_Segs': round(delta_t, 4)
                })
                ultimo_onset = onset_atual
                
        # Se apesar da limpeza o arquivo der mais de 30, avisamos.
        if contador_faces > 30:
            print(f"[ALERTA] {paciente_id} ainda possui {contador_faces} faces mapeadas.")
        else:
            print(f"[{paciente_id}] -> {contador_faces} faces mapeadas.")
            
        pacientes_processados += 1
        
    except Exception as e:
        print(f"[ERRO] Falha ao processar {paciente_id}: {e}")

df_onsets = pd.DataFrame(dados_onsets)
caminho_csv = os.path.join(DIR_RESULTS, 'tabela_tempos_estimulos_faces_limpa.csv')
df_onsets.to_csv(caminho_csv, index=False)

print("\n" + "="*80)
print("EXTRAÇÃO DEFINITIVA CONCLUÍDA!")
print(f"Total de pacientes na matriz: {pacientes_processados}")
print(f"Arquivo Salvo: {caminho_csv}")
print("="*80)

================================================================================
Iniciando Extração Definitiva (Com Correções Forenses)...
================================================================================
[TEA_G_26] -> 30 faces mapeadas.
[TEA_G_28] -> 30 faces mapeadas.
[TEA_G_30] -> 30 faces mapeadas.
[TEA_G_40] -> 30 faces mapeadas.
[TEA_L_16] -> 30 faces mapeadas.
[TEA_L_17] -> 30 faces mapeadas.
[TEA_L_24] -> 30 faces mapeadas.
[TEA_L_25] -> 30 faces recuperadas via 'FACE'.
[ALERTA] TEA_L_27 ainda possui 31 faces mapeadas.
[TEA_L_29] -> 30 faces mapeadas.
[TEA_L_32] -> 30 faces mapeadas.
[TEA_L_46] -> 30 faces mapeadas.
[TEA_M_15] -> 30 faces mapeadas.
[TEA_M_18] -> 30 faces mapeadas.
[TEA_M_19] -> 30 faces mapeadas.
[TEA_M_20] -> 30 faces mapeadas.
[TEA_M_21] -> 30 faces mapeadas.
[TEA_M_22] -> 30 faces mapeadas.
[ALERTA] control_12 ainda possui 31 faces mapeadas.
[control_13] -> 30 faces mapeadas.
[control_35] -> 30 faces mapeadas.
[control_36] -> 30 faces mapeadas.
[control_37] -> 30 faces mapeadas.
[control_38] -> 30 faces mapeadas.
[control_39] -> 30 faces mapeadas.
[ALERTA] control_41 ainda possui 36 faces mapeadas.
[control_42] -> 30 faces mapeadas.
[control_43] -> 30 faces mapeadas.
[control_44] -> 30 faces mapeadas.
[control_47] -> 30 faces mapeadas.
[control_48] -> 30 faces mapeadas.
[control_49] -> 30 faces mapeadas.
[control_50] -> 30 faces mapeadas.
[control_51] -> 30 faces mapeadas.
[control_54] -> 30 faces mapeadas.
[control_55] -> 30 faces mapeadas.
[control_56] -> 30 faces mapeadas.
[control_57] -> 30 faces mapeadas.
[control_58] -> 30 faces mapeadas.
[control_59] -> 30 faces mapeadas.
[control_60] -> 30 faces mapeadas.
[control_61] -> 30 faces mapeadas.

================================================================================
EXTRAÇÃO DEFINITIVA CONCLUÍDA!
Total de pacientes na matriz: 42
Arquivo Salvo: ../results/tabela_tempos_estimulos_faces_limpa.csv
================================================================================

In [8]:
import os
import pandas as pd
import mne
import warnings

warnings.filterwarnings('ignore')
mne.set_log_level('WARNING')

print("\n" + "="*80)
print("Iniciando Extração Rigorosa (Forçando Exatamente 30 Faces)...")
print("="*80)

DIR_RAW = '../data/raw/'
DIR_RESULTS = '../results/'

# Pacientes a excluir
ARQUIVOS_EXCLUIDOS = ['control_14-sem marcacoes', 'TEA_M_22_1']
ESTIMULOS_ALVO = ['FF', 'FN', 'FR']

os.makedirs(DIR_RESULTS, exist_ok=True)
arquivos_edf = sorted([f for f in os.listdir(DIR_RAW) if f.lower().endswith('.edf')])
dados_onsets = []
pacientes_processados = 0

for arquivo in arquivos_edf:
    paciente_id = arquivo.replace('.edf', '')
    if paciente_id in ARQUIVOS_EXCLUIDOS: continue
        
    caminho_completo = os.path.join(DIR_RAW, arquivo)
    
    try:
        raw = mne.io.read_raw_edf(caminho_completo, preload=False, encoding='latin1', verbose=False)
        
        eventos_paciente = []
        
        # 1. VARREDURA BRUTA (Captura tudo o que for válido)
        for ann in raw.annotations:
            descricao = ann['description'].strip().upper()
            onset = ann['onset']
            duracao = ann['duration']
            
            # Regra Restrita ao TEA_L_16: Traduzir letras soltas
            if paciente_id == 'TEA_L_16':
                if descricao == 'F': descricao = 'FF'
                elif descricao == 'N': descricao = 'FN'
                elif descricao == 'R': descricao = 'FR'
                
            # Regra Restrita ao TEA_L_25: Capturar o marcador genérico
            if paciente_id == 'TEA_L_25' and descricao == 'FACE':
                eventos_paciente.append({'estimulo': 'FACE', 'onset': onset, 'duracao': duracao})
                continue
                
            # Restante dos pacientes: Capturar apenas os alvos
            if descricao in ESTIMULOS_ALVO:
                eventos_paciente.append({'estimulo': descricao, 'onset': onset, 'duracao': duracao})
                
        # 2. FILTRAGEM CIRÚRGICA (Garantir 30 Faces Exatas)
        eventos_filtrados = []
        
        if paciente_id == 'TEA_L_25':
            # Pega exatamente os 30 primeiros blocos genéricos e deduz a emoção
            for i, ev in enumerate(eventos_paciente[:30]):
                est = 'FF' if i < 10 else ('FN' if i < 20 else 'FR')
                eventos_filtrados.append({'estimulo': est, 'onset': ev['onset'], 'duracao': ev['duracao']})
        else:
            # Separa por emoção
            ff_list = [ev for ev in eventos_paciente if ev['estimulo'] == 'FF']
            fn_list = [ev for ev in eventos_paciente if ev['estimulo'] == 'FN']
            fr_list = [ev for ev in eventos_paciente if ev['estimulo'] == 'FR']
            
            # A REGRA DOS ÚLTIMOS 10: Se houver mais de 10, mantém apenas os últimos 10 (as tentativas válidas finais)
            ff_list = ff_list[-10:] if len(ff_list) > 10 else ff_list
            fn_list = fn_list[-10:] if len(fn_list) > 10 else fn_list
            fr_list = fr_list[-10:] if len(fr_list) > 10 else fr_list
            
            # Reagrupa e ordena cronologicamente pelo onset
            eventos_filtrados = sorted(ff_list + fn_list + fr_list, key=lambda x: x['onset'])

        # 3. CÁLCULO DO DELTA T E MONTAGEM DA TABELA
        ultimo_onset = None
        for i, ev in enumerate(eventos_filtrados):
            onset_atual = ev['onset']
            delta_t = onset_atual - ultimo_onset if ultimo_onset is not None else 0.0
            
            dados_onsets.append({
                'Paciente_ID': paciente_id,
                'Face_Ordem': i + 1,
                'Estimulo': ev['estimulo'],
                'Onset_Segundos': round(onset_atual, 4),
                'Duracao_Segundos': round(ev['duracao'], 4),
                'Delta_T_Anterior_Segs': round(delta_t, 4)
            })
            ultimo_onset = onset_atual
            
        print(f"[{paciente_id}] -> {len(eventos_filtrados)} faces mapeadas e trancadas.")
        pacientes_processados += 1
        
    except Exception as e:
        print(f"[ERRO] Falha ao processar {paciente_id}: {e}")

df_onsets = pd.DataFrame(dados_onsets)
caminho_csv = os.path.join(DIR_RESULTS, 'tabela_tempos_estimulos_faces_limpa.csv')
df_onsets.to_csv(caminho_csv, index=False)

print("\n" + "="*80)
print("ALINHAMENTO CONCLUÍDO!")
print(f"Total de pacientes na matriz: {pacientes_processados}")
print(f"Arquivo Salvo: {caminho_csv}")
print("="*80)

================================================================================
Iniciando Extração Rigorosa (Forçando Exatamente 30 Faces)...
================================================================================
[TEA_G_26] -> 30 faces mapeadas e trancadas.
[TEA_G_28] -> 29 faces mapeadas e trancadas.
[TEA_G_30] -> 30 faces mapeadas e trancadas.
[TEA_G_40] -> 30 faces mapeadas e trancadas.
[TEA_L_16] -> 30 faces mapeadas e trancadas.
[TEA_L_17] -> 30 faces mapeadas e trancadas.
[TEA_L_24] -> 30 faces mapeadas e trancadas.
[TEA_L_25] -> 30 faces mapeadas e trancadas.
[TEA_L_27] -> 30 faces mapeadas e trancadas.
[TEA_L_29] -> 30 faces mapeadas e trancadas.
[TEA_L_32] -> 30 faces mapeadas e trancadas.
[TEA_L_46] -> 30 faces mapeadas e trancadas.
[TEA_M_15] -> 30 faces mapeadas e trancadas.
[TEA_M_18] -> 30 faces mapeadas e trancadas.
[TEA_M_19] -> 30 faces mapeadas e trancadas.
[TEA_M_20] -> 30 faces mapeadas e trancadas.
[TEA_M_21] -> 30 faces mapeadas e trancadas.
[TEA_M_22] -> 30 faces mapeadas e trancadas.
[control_12] -> 30 faces mapeadas e trancadas.
[control_13] -> 30 faces mapeadas e trancadas.
[control_35] -> 30 faces mapeadas e trancadas.
[control_36] -> 30 faces mapeadas e trancadas.
[control_37] -> 30 faces mapeadas e trancadas.
[control_38] -> 30 faces mapeadas e trancadas.
[control_39] -> 30 faces mapeadas e trancadas.
[control_41] -> 30 faces mapeadas e trancadas.
[control_42] -> 30 faces mapeadas e trancadas.
[control_43] -> 30 faces mapeadas e trancadas.
[control_44] -> 30 faces mapeadas e trancadas.
[control_47] -> 30 faces mapeadas e trancadas.
[control_48] -> 30 faces mapeadas e trancadas.
[control_49] -> 30 faces mapeadas e trancadas.
[control_50] -> 30 faces mapeadas e trancadas.
[control_51] -> 30 faces mapeadas e trancadas.
[control_54] -> 30 faces mapeadas e trancadas.
[control_55] -> 30 faces mapeadas e trancadas.
[control_56] -> 30 faces mapeadas e trancadas.
[control_57] -> 30 faces mapeadas e trancadas.
[control_58] -> 30 faces mapeadas e trancadas.
[control_59] -> 30 faces mapeadas e trancadas.
[control_60] -> 30 faces mapeadas e trancadas.
[control_61] -> 30 faces mapeadas e trancadas.

================================================================================
ALINHAMENTO CONCLUÍDO!
Total de pacientes na matriz: 42
Arquivo Salvo: ../results/tabela_tempos_estimulos_faces_limpa.csv
================================================================================

In [9]:
import os
import pandas as pd
import mne
import warnings

# Silenciar avisos para manter o terminal limpo
warnings.filterwarnings('ignore')
mne.set_log_level('WARNING')

print("\n" + "="*80)
print("ALINHAMENTO FINAL: EXTRAÇÃO RIGOROSA (FOCO NO 30 PERFEITO)")
print("="*80)

DIR_RAW = '../data/raw/'
DIR_RESULTS = '../results/'

# Pacientes a excluir (sem marcações ou corrompidos)
ARQUIVOS_EXCLUIDOS = ['control_14-sem marcacoes', 'TEA_M_22_1']

os.makedirs(DIR_RESULTS, exist_ok=True)
arquivos_edf = sorted([f for f in os.listdir(DIR_RAW) if f.lower().endswith('.edf')])
dados_onsets = []
pacientes_processados = 0

for arquivo in arquivos_edf:
    paciente_id = arquivo.replace('.edf', '')
    if paciente_id in ARQUIVOS_EXCLUIDOS: continue
        
    caminho_completo = os.path.join(DIR_RAW, arquivo)
    
    try:
        raw = mne.io.read_raw_edf(caminho_completo, preload=False, encoding='latin1', verbose=False)
        eventos_raw = []
        
        # 1. VARREDURA INDIVIDUALIZADA
        for ann in raw.annotations:
            desc = ann['description'].strip().upper()
            onset = ann['onset']
            dur = ann['duration']
            
            # --- REGRA PARA TEA_L_16 (Mapear letras soltas) ---
            if paciente_id == 'TEA_L_16':
                if desc == 'F': desc = 'FF'
                elif desc == 'N': desc = 'FN'
                elif desc == 'R': desc = 'FR'
            
            # --- REGRA PARA TEA_L_25 (Mapear marcador genérico) ---
            if paciente_id == 'TEA_L_25' and desc == 'FACE':
                eventos_raw.append({'estimulo': 'FACE', 'onset': onset, 'duracao': dur})
                continue
                
            # --- REGRA PADRÃO (Para todos os outros, incluindo TEA_G_28) ---
            if desc in ['FF', 'FN', 'FR']:
                eventos_raw.append({'estimulo': desc, 'onset': onset, 'duracao': dur})
                
        # 2. FILTRAGEM E CATEGORIZAÇÃO
        eventos_finais = []
        
        if paciente_id == 'TEA_L_25':
            # Recupera as 30 primeiras e rotula por ordem
            for i, ev in enumerate(eventos_raw[:30]):
                label = 'FF' if i < 10 else ('FN' if i < 20 else 'FR')
                eventos_finais.append({'estimulo': label, 'onset': ev['onset'], 'duracao': ev['duracao']})
        else:
            # Separa por emoção e aplica a REGRA DOS ÚLTIMOS 10 (para limpar control_41 e TEA_L_27)
            felizes = [e for e in eventos_raw if e['estimulo'] == 'FF'][-10:]
            neutras = [e for e in eventos_raw if e['estimulo'] == 'FN'][-10:]
            raiva   = [e for e in eventos_raw if e['estimulo'] == 'FR'][-10:]
            
            # Reorganiza na ordem do tempo
            eventos_finais = sorted(felizes + neutras + raiva, key=lambda x: x['onset'])

        # 3. VALIDAÇÃO E MONTAGEM DO CSV
        if len(eventos_finais) != 30:
            print(f"[ALERTA] {paciente_id} ficou com {len(eventos_finais)} faces. (FF:{len(felizes)} | FN:{len(neutras)} | FR:{len(raiva)})")
        else:
            print(f"[{paciente_id}] -> {len(eventos_finais)} faces OK.")
            
        ultimo_onset = None
        for i, ev in enumerate(eventos_finais):
            onset_atual = ev['onset']
            delta_t = onset_atual - ultimo_onset if ultimo_onset is not None else 0.0
            
            dados_onsets.append({
                'Paciente_ID': paciente_id,
                'Face_Ordem': i + 1,
                'Estimulo': ev['estimulo'],
                'Onset_Segundos': round(onset_atual, 4),
                'Duracao_Segundos': round(ev['duracao'], 4),
                'Delta_T_Anterior_Segs': round(delta_t, 4)
            })
            ultimo_onset = onset_atual
            
        pacientes_processados += 1
        
    except Exception as e:
        print(f"[ERRO] Falha ao processar {paciente_id}: {e}")

# 4. SALVAMENTO
df_final = pd.DataFrame(dados_onsets)
caminho_csv = os.path.join(DIR_RESULTS, 'tabela_tempos_estimulos_faces_limpa.csv')
df_final.to_csv(caminho_csv, index=False)

print("\n" + "="*80)
print(f"CONCLUÍDO: {pacientes_processados} pacientes processados.")
print(f"Matriz salva em: {caminho_csv}")
print("="*80)

================================================================================
ALINHAMENTO FINAL: EXTRAÇÃO RIGOROSA (FOCO NO 30 PERFEITO)
================================================================================
[TEA_G_26] -> 30 faces OK.
[ALERTA] TEA_G_28 ficou com 29 faces. (FF:10 | FN:10 | FR:9)
[TEA_G_30] -> 30 faces OK.
[TEA_G_40] -> 30 faces OK.
[TEA_L_16] -> 30 faces OK.
[TEA_L_17] -> 30 faces OK.
[TEA_L_24] -> 30 faces OK.
[TEA_L_25] -> 30 faces OK.
[TEA_L_27] -> 30 faces OK.
[TEA_L_29] -> 30 faces OK.
[TEA_L_32] -> 30 faces OK.
[TEA_L_46] -> 30 faces OK.
[TEA_M_15] -> 30 faces OK.
[TEA_M_18] -> 30 faces OK.
[TEA_M_19] -> 30 faces OK.
[TEA_M_20] -> 30 faces OK.
[TEA_M_21] -> 30 faces OK.
[TEA_M_22] -> 30 faces OK.
[control_12] -> 30 faces OK.
[control_13] -> 30 faces OK.
[control_35] -> 30 faces OK.
[control_36] -> 30 faces OK.
[control_37] -> 30 faces OK.
[control_38] -> 30 faces OK.
[control_39] -> 30 faces OK.
[control_41] -> 30 faces OK.
[control_42] -> 30 faces OK.
[control_43] -> 30 faces OK.
[control_44] -> 30 faces OK.
[control_47] -> 30 faces OK.
[control_48] -> 30 faces OK.
[control_49] -> 30 faces OK.
[control_50] -> 30 faces OK.
[control_51] -> 30 faces OK.
[control_54] -> 30 faces OK.
[control_55] -> 30 faces OK.
[control_56] -> 30 faces OK.
[control_57] -> 30 faces OK.
[control_58] -> 30 faces OK.
[control_59] -> 30 faces OK.
[control_60] -> 30 faces OK.
[control_61] -> 30 faces OK.

================================================================================
CONCLUÍDO: 42 pacientes processados.
Matriz salva em: ../results/tabela_tempos_estimulos_faces_limpa.csv
================================================================================

In [10]:
import os
import pandas as pd
import mne
import warnings

warnings.filterwarnings('ignore')
mne.set_log_level('WARNING')

print("\n" + "="*80)
print("ALINHAMENTO FINAL: EXTRAÇÃO RIGOROSA E INTELIGENTE")
print("="*80)

DIR_RAW = '../data/raw/'
DIR_RESULTS = '../results/'

ARQUIVOS_EXCLUIDOS = ['control_14-sem marcacoes', 'TEA_M_22_1']

os.makedirs(DIR_RESULTS, exist_ok=True)
arquivos_edf = sorted([f for f in os.listdir(DIR_RAW) if f.lower().endswith('.edf')])
dados_onsets = []
pacientes_processados = 0

for arquivo in arquivos_edf:
    paciente_id = arquivo.replace('.edf', '')
    if paciente_id in ARQUIVOS_EXCLUIDOS: continue
        
    caminho_completo = os.path.join(DIR_RAW, arquivo)
    
    try:
        raw = mne.io.read_raw_edf(caminho_completo, preload=False, encoding='latin1', verbose=False)
        eventos_raw = []
        
        # 1. VARREDURA 
        for ann in raw.annotations:
            desc = ann['description'].strip().upper()
            onset = ann['onset']
            dur = ann['duration']
            
            if paciente_id == 'TEA_L_16':
                if desc == 'F': desc = 'FF'
                elif desc == 'N': desc = 'FN'
                elif desc == 'R': desc = 'FR'
            
            if paciente_id == 'TEA_L_25' and desc == 'FACE':
                eventos_raw.append({'estimulo': 'FACE', 'onset': onset, 'duracao': dur})
                continue
                
            if desc in ['FF', 'FN', 'FR']:
                eventos_raw.append({'estimulo': desc, 'onset': onset, 'duracao': dur})
                
        # 2. FILTRAGEM INTELIGENTE
        eventos_finais = []
        
        if paciente_id == 'TEA_L_25':
            for i, ev in enumerate(eventos_raw[:30]):
                label = 'FF' if i < 10 else ('FN' if i < 20 else 'FR')
                eventos_finais.append({'estimulo': label, 'onset': ev['onset'], 'duracao': ev['duracao']})
        else:
            # SE HOUVER EXCESSO (> 30), aplica o filtro de limpeza dos últimos 10
            if len(eventos_raw) > 30:
                felizes = [e for e in eventos_raw if e['estimulo'] == 'FF'][-10:]
                neutras = [e for e in eventos_raw if e['estimulo'] == 'FN'][-10:]
                raiva   = [e for e in eventos_raw if e['estimulo'] == 'FR'][-10:]
                eventos_finais = sorted(felizes + neutras + raiva, key=lambda x: x['onset'])
            # SE TIVER 30 OU MENOS, preserva a cronologia absoluta do equipamento
            else:
                eventos_finais = sorted(eventos_raw, key=lambda x: x['onset'])

        # 3. VALIDAÇÃO E MONTAGEM
        if len(eventos_finais) != 30:
            print(f"[ALERTA] {paciente_id} tem {len(eventos_finais)} faces.")
        else:
            print(f"[{paciente_id}] -> {len(eventos_finais)} faces OK.")
            
        ultimo_onset = None
        for i, ev in enumerate(eventos_finais):
            onset_atual = ev['onset']
            delta_t = onset_atual - ultimo_onset if ultimo_onset is not None else 0.0
            
            dados_onsets.append({
                'Paciente_ID': paciente_id,
                'Face_Ordem': i + 1,
                'Estimulo': ev['estimulo'],
                'Onset_Segundos': round(onset_atual, 4),
                'Duracao_Segundos': round(ev['duracao'], 4),
                'Delta_T_Anterior_Segs': round(delta_t, 4)
            })
            ultimo_onset = onset_atual
            
        pacientes_processados += 1
        
    except Exception as e:
        print(f"[ERRO] Falha ao processar {paciente_id}: {e}")

df_final = pd.DataFrame(dados_onsets)
caminho_csv = os.path.join(DIR_RESULTS, 'tabela_tempos_estimulos_faces_limpa.csv')
df_final.to_csv(caminho_csv, index=False)

print("\n" + "="*80)
print(f"CONCLUÍDO! Matriz salva em: {caminho_csv}")
print("="*80)

================================================================================
ALINHAMENTO FINAL: EXTRAÇÃO RIGOROSA E INTELIGENTE
================================================================================
[TEA_G_26] -> 30 faces OK.
[TEA_G_28] -> 30 faces OK.
[TEA_G_30] -> 30 faces OK.
[TEA_G_40] -> 30 faces OK.
[TEA_L_16] -> 30 faces OK.
[TEA_L_17] -> 30 faces OK.
[TEA_L_24] -> 30 faces OK.
[TEA_L_25] -> 30 faces OK.
[TEA_L_27] -> 30 faces OK.
[TEA_L_29] -> 30 faces OK.
[TEA_L_32] -> 30 faces OK.
[TEA_L_46] -> 30 faces OK.
[TEA_M_15] -> 30 faces OK.
[TEA_M_18] -> 30 faces OK.
[TEA_M_19] -> 30 faces OK.
[TEA_M_20] -> 30 faces OK.
[TEA_M_21] -> 30 faces OK.
[TEA_M_22] -> 30 faces OK.
[control_12] -> 30 faces OK.
[control_13] -> 30 faces OK.
[control_35] -> 30 faces OK.
[control_36] -> 30 faces OK.
[control_37] -> 30 faces OK.
[control_38] -> 30 faces OK.
[control_39] -> 30 faces OK.
[control_41] -> 30 faces OK.
[control_42] -> 30 faces OK.
[control_43] -> 30 faces OK.
[control_44] -> 30 faces OK.
[control_47] -> 30 faces OK.
[control_48] -> 30 faces OK.
[control_49] -> 30 faces OK.
[control_50] -> 30 faces OK.
[control_51] -> 30 faces OK.
[control_54] -> 30 faces OK.
[control_55] -> 30 faces OK.
[control_56] -> 30 faces OK.
[control_57] -> 30 faces OK.
[control_58] -> 30 faces OK.
[control_59] -> 30 faces OK.
[control_60] -> 30 faces OK.
[control_61] -> 30 faces OK.

================================================================================
CONCLUÍDO! Matriz salva em: ../results/tabela_tempos_estimulos_faces_limpa.csv
================================================================================